import "./globals.css"
import type { Metadata } from "next"
import { PrivyAuthProvider } from "./providers";
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <PrivyAuthProvider>
            {children}
          </PrivyAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
